srmGpaCalculator sem class.
STATUS: working. But need to work on swing component
error: It was showing container component earlier bu now it is not working